apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-router.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "llm-router.fullname" . }}
data:
  {{- range $key, $value := .Values.config }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}