apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-router.fullname" . }}-config-models
  labels:
    app.kubernetes.io/name: {{ include "llm-router.fullname" . }}
data:
{{- range $key, $value := .Values.configModels }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}