{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-router.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "llm-router.fullname" . }}-redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "llm-router.fullname" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "llm-router.fullname" . }}-redis
    spec:
      containers:
          - name: redis
            image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
            imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.redis.service.port }}
  {{- end }}