apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "llm-router.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: llm-router
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "llm-router.fullname" . }}